### ISSUE TITLE
DataRequest response is observed always on DispatchQueue.main ignoring any subscribeOn

### ISSUE THREAD

**Issue by rrodrigues** [RxSwiftCommunity/RxAlamofire#147]
The `DataRequest` response is always observed on `DispatchQueue.main`.
For example: 
```
let queue = DispatchQueue(label: "RxAlamofireTest", qos: .background)
let schedule = SerialDispatchQueueScheduler(queue: queue, internalSerialQueueName: "RxAlamofireTest")
let urlString = "https://jsonplaceholder.typicode.com/todos/1"
let bag = DisposeBag()
        
request(.get, urlString)
    .subscribeOn(schedule)
    .do(onNext: { (_) in
        print("[1] isMainThread: \(Thread.isMainThread)")
    })
    .data()
    .subscribe(onNext: { (_) in
        print("[2] isMainThread: \(Thread.isMainThread)")
    })
    .disposed(by: bag)
```

This seems to be because there isn't any queue being passed along when calling `DataRequest.response(queue: responseSerializer: completionHandler)`, which makes it to default to the `DispatchQueue.main`.

Since there is a `.subscribeOn(schedule)` shouldn't the `subscribe(onNext:)` be done on the `schedule` thread instead of being received on the `DispatchQueue.main`?

**Comment by epatey** [comment]
@rrodrigues , this is expected behavior. The wording is confusing. `.subscribeOn` doesn't specify on which queue/scheduler to deliver events for the subscription. Instead, it means where to execute code associated with _initiating_ the subscription.

You will get the behavior you're looking for if you simply replace your `.subscribeOn` with `.observeOn`.

**Comment by rrodrigues** [comment]
@epatey yes `.subscribeOn` should specify on which thread the whole chain starts processing, `.observeOn` allows to switch between threads.

I'm sorry if I wasn't able to explain me correctly.

What I think is not the expected behaviour is that when you create a sequence of operations like:
```
request(.get, urlString)
    .subscribeOn(schedule) // <= defines which thread the operation should be done
    .data()
    .subscribe(onNext: { (_) in
        // the current thread here should be one defined above by .subscribeOn(schedule)
        // and is not, this is run on the MainThread.
    })
    .disposed(by: bag)
```
if you don't call `.observeOn` anywhere the `.subscribe(onNext:` should be done on the initial thread/queue defined by `.subscribeOn`.

What is happening here is that on the `.data()` call internally Alamofire is calling `DispatchQueue.main.async` and this changes the execution thread/queue.
In my opinion should not be done, the queue where the operation started should be the done used when dispatching the `DataRequest` response.

**Comment by freak4pc** [comment]
> if you don't call .observeOn anywhere the .subscribe(onNext: should be done on the initial thread/queue defined by .subscribeOn.

I don't think this makes sense because it doesn't happen like that anywhere in Rx resource processing. You are responsible for deciding where to process and where to receive events. 

It really shouldn't (and probably can't) be a library's responsibility to force you to use some scheduler you used earlier, plus library doesn't know which scheduler it's running on usually, since it shouldn't know (it's an implementation detail).

**Comment by rrodrigues** [comment]
ok. 
So my understanding is wrong then.
Thanks for the clarification.
