### ISSUE TITLE
Cannot get response data when error occurred

### ISSUE THREAD

**Issue by rickyngk** [RxSwiftCommunity/RxAlamofire#29]
In case I'd like to get error status, I have to do a hack:

``` swift
.asDriver(onErrorRecover: { (error) -> Driver<AnyObject> in
    let e:NSObject = error as! NSObject;
    if let userInfo = e.valueForKey("_userInfo") as? NSDictionary {
        if let statusCode = userInfo["StatusCode"] as? Int {
            return Driver.just(PKApiError.error(statusCode));
        }
    }
    return Driver.just(PKApiError.defaultError())
})
```

I dunno if we have a better solution. Anyway, I find no way to get response data, e.g: 

``` json
{
  "error" : {
    "status" : 400,
    "message" : "Fail to authenticate with Facebook"
  }
}
```

After digging in code, I see: 

``` swift
case .Failure(let error):
    observer.on(.Error(error as ErrorType))
```

I think that is the reason why. IMO it'd better if we embed explicitly status code and data (`packedResponse .data`) here

**Comment by bontoJR** [comment]
This is a good point, I am definitely open to add extra information on status codes giving back an error. 👍

**Comment by juanuribeo13** [comment]
+1

**Comment by andreaantonioni** [comment]
Sorry guys, now how can I get the json when an error occurs?

**Comment by d370urn3ur** [comment]
I ended up cloning the extension function and passing in a custom error that takes the result code + body data.  It is very specific for my use case (only using the `json()` func to make my request) and I had to override several other extension functions to be able to direct the request to use my custom response handler, but it might be useful for someone who is working on a pull request :

- I customized the reactive json() to be able to pass in URLRequestConvertible, otherwise you have to create your own custom hook into RxAlamofire (by overriding json(_:,_:,parameters:,encoding:,headers:) for example)

```
extension Reactive where Base: SessionManager {
    public func json(urlRequest: URLRequestConvertible) -> Observable<Any> {
        return request(urlRequest: urlRequest)
            .flatMap { $0.rx.jsonWithErrorData() }
    }
}

extension Reactive where Base: DataRequest {
    
    // Have to do this because validateSuccessfulResponse() in RxAlamofire has `internal` visibility
    func validateSuccessfulResponse2() -> DataRequest {
        return self.base.validate(statusCode: 200 ..< 300)
    }
    
    public func jsonWithErrorData(options: JSONSerialization.ReadingOptions = .allowFragments) -> Observable<Any> {
        return resultWithErrorData(responseSerializer: Base.jsonResponseSerializer(options: options))
    }
    
    public func resultWithErrorData<T: DataResponseSerializerProtocol>(queue: DispatchQueue? = nil, responseSerializer: T) -> Observable<T.SerializedObject> {
        return Observable.create { observer in
            let dataRequest = self.validateSuccessfulResponse2()
                .response(queue: queue, responseSerializer: responseSerializer) { (packedResponse) -> Void in
                    switch packedResponse.result {
                    case .success(let result):
                        if let _ = packedResponse.response {
                            observer.on(.next(result))
                        }
                        else {
                            observer.on(.error(RxAlamofireUnknownError))
                        }
                        observer.on(.completed)
                    case .failure(let error):
                        let code = (error as? AFError)?.responseCode
                        let bodyData = packedResponse.data
                        observer.on(.error(CustomError.NetworkError(code: code, bodyData: bodyData)))
                    }
            }
            return Disposables.create {
                dataRequest.cancel()
            }
        }
    }
}
```

To recover NetworkError I do like 

```
if err is CustomError {
   switch((err as! CustomError)) {
   case .CustomError(let code, let bodyData):
      // do your thing
   }
}
```

**Comment by fmaylinch** [comment]
Can this be done now without hacking?

**Comment by anonrig** [comment]
Any updates on this?

**Comment by freak4pc** [comment]
Hey - if anyone is willing to open a PR, I can review it. Thanks :)

**Comment by anonrig** [comment]
Can you reopen this issue @freak4pc

**Comment by freak4pc** [comment]
Better to open a new post with new information. The original issue is almost 3 years old. Thanks :)

**Comment by gorbat-o** [comment]
Still the same issue anyway
even affter 3 years 😅

**Comment by anonrig** [comment]
lol opensource is awesome...

**Comment by freak4pc** [comment]
I guess you have two options @anonrig:

1. Fix it yourself and submit a PR
2. Write a douchie comment about the free work of hundreds of contributors

We all know what you picked. 

Note that the last comment here mentioned this issue is over 3 years old, and that if someone is having the same issue, they should **open a new issue**. 

Please do as I mentioned above if it's still bothering you. 

Locking.
