### ISSUE TITLE
Making a request with only the url as argument doesn't work

### ISSUE THREAD

**Issue by ajandrade** [RxSwiftCommunity/RxAlamofire#74]
Hi guys, 

I'm trying to implement a router like described on Alamofire documentation (CRUD & Auth section).

After going through RxAlamofire code I found this:
`public func request(urlRequest: URLRequestConvertible) -> RxSwift.Observable<Alamofire.DataRequest>`
but I can't use it because it gives me the following error: "Missing argument for parameter #2 in call".

**Comment by freak4pc** [comment]
Hey @ajandrade 
Seems to be working fine here. 
Don't forget you have to add a responseJSON since you're getting back a DataRequest from this method. 

<img width="631" alt="903fba4c-bc0e-4473-9e86-c21c3927af0f" src="https://cloud.githubusercontent.com/assets/605076/26467482/728b5f0a-419b-11e7-9f79-0c3e427b071f.png">

You would probably be better off using `RxAlamofire.request(.get, "http://google.com")` unless there's a specific reason here.
