### ISSUE TITLE
Encoding multipart form data

### ISSUE THREAD

**Issue by vzsg** [RxSwiftCommunity/RxAlamofire#84]
There's an asynchronous function that the wrapper currently doesn't support: [multipart form uploads](https://github.com/Alamofire/Alamofire#uploading-multipart-form-data).

I wrote a short extension to rectify this for my project, which is available [here](https://gist.github.com/vzsg/b1a7405c987bdf18cc9035591ea2f58c).  
The returned `Observable<UploadRequest>` can be then flatMapped into `rx.data()` or other RXAlamofire methods.

If you think it's useful, please consider including it in the library. I can turn this into a PR if that helps.

**Comment by freak4pc** [comment]
Hey @vzsg , Thanks for the code ! 
I think this is highly useful and I'd personally love to see it as a full-fledged PR. 

The only thing I'm wondering on is if the naming of the method makes sense - Since we want to remain as close as possible to original Alamofire terms so it's easier to discover. So I would imagine this making more sense as some overload of `upload`. What do you think ?

**Comment by vzsg** [comment]
I'm okay with changing the name to match the original. (Locally I went with the verbose name so others can clearly see that this is not the actual upload yet, but I don't have a preference.)

**Comment by freak4pc** [comment]
Sorry for the uber-delay on replying here. Was this ever addresses or this feature is still needed?

**Comment by vzsg** [comment]
Well, I'm still using my extension in production, and it didn't magically appear in this repo, so yeah, I think this is still on. :) All that's missing is a nice name for the new function.

**Comment by freak4pc** [comment]
How do you call it in your extension ?

**Comment by vzsg** [comment]
I made the PR using Alamofire's naming and part of their documentation.
Please review if you have the time.
