### ISSUE TITLE
when i post application/json parameters, it return nil.

### ISSUE THREAD

**Issue by kongxiangjia305** [RxSwiftCommunity/RxAlamofire#96]
when i post application/json parameters, it return nil.

**Comment by freak4pc** [comment]
This is not a very useful issue :) 
Please attach some code, explanation, etc.

**Comment by kongxiangjia305** [comment]
https://www.dropbox.com/s/6s7crui8zbibami/uploading.png?dl=0

**Comment by kongxiangjia305** [comment]
pls check this url. it is postman's example

**Comment by kongxiangjia305** [comment]
when i use the api, it return nil in app

**Comment by freak4pc** [comment]
We won't be able to help without reproducible code, probably

**Comment by kongxiangjia305** [comment]
return manager.rx.responseData(.post, url, parameters: params, encoding: JSONEncoding.default, headers: [“Content-Type”: “application/json”])
            .map{
                let request = $0
                print(request)
                print(String(data: $1, encoding: .utf8))
                return JSON(data: $1)
        }

**Comment by freak4pc** [comment]
Hey @kongxiangjia305 
This seems to be an issue with your code, and not with the library.
We try to have issues opened mainly for library-specific issues.

When I use your URL with just a Content-Type header, it fails as well. Please do notice your Postman request has 7 different headers, so maybe authentication is what you're missing.

If you have any usage-specific questions, please check out the RxSwift slack @ https://rxswift-slack.herokuapp.com

Thanks ! 
Shai

**Comment by mobilestar0223** [comment]
Hi
I'm @kongxiangjia305's partner and I have same issue.
I have tried with that API and I set Content-Type to "application/json", but it always return nil.
I also have tried with other content-type, but always got same error.

I have checked `print(request)` log and I got idea that request header's content-type was "text/html" even I set to application/json.
It seems setting content-type header doesn't works well.

Please check and test this.

Thanks

**Comment by freak4pc** [comment]
As I said, this is not a problem with application/json, it has to be a problem with some authentication headers, etc. 

I've used your exact code in a test project on both GET and POST and i'm getting valid JSON. 

GET:
![8e5ec29e-4424-45da-9aa8-051b63bfae2b](https://user-images.githubusercontent.com/605076/33942907-1a32fd62-e020-11e7-9648-794bf0b25f26.png)

POST:
![d1ff022e-7d6e-41eb-ae6e-27bd11f41c26](https://user-images.githubusercontent.com/605076/33942956-4260a4e2-e020-11e7-8428-2664dfb2dc7e.png)


We don't provide code-level support in Issues here, since we use GitHub Issues just for bugs in the library itself, so I suggest:
1. Please confirm your request is valid
2. If you have any code-specific issues, check out our slack channel.

Good luck!

**Comment by mobilestar0223** [comment]
I have attached screenshot and please check my code and printed result.
![screen shot 2017-12-13 at 10 16 49 pm](https://user-images.githubusercontent.com/18617203/33943215-6ccad184-e053-11e7-8a21-0d828165b36b.png)

**Comment by freak4pc** [comment]
Hey @mobilestar0223 
Sorry, I have to stress this out - It's impossible for Contributors to spend time on code-level issues. We can't support development efforts of other developers or companies :) 

If this was a reproduced bug, I would definitely love to look into it and fix it inside RxAlamofire, but since this is specific to your code base, I suggest you ask the question on our Slack channel.
